# Generated by Django 2.1.7 on 2019-04-25 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('debut_date', models.DateField(verbose_name='debut date')),
                ('video_count', models.IntegerField(default=0)),
                ('total_view_count', models.IntegerField(default=0)),
                ('company', models.CharField(max_length=200)),
                ('current_member_count', models.IntegerField(default=0)),
                ('picture', models.ImageField(upload_to='gallery')),
                ('yt_channel_id', models.CharField(max_length=200)),
                ('pic_url', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(choices=[('G', 'Female'), ('B', 'Male'), ('M', 'Mixed')], default='G', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('upload_date', models.DateField(verbose_name='upload date')),
                ('view_count', models.IntegerField(default=0)),
                ('yt_video_id', models.CharField(max_length=200)),
                ('thumbnail_url', models.CharField(max_length=200, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='stats.Group')),
            ],
        ),
    ]
