# Generated by Django 2.1.7 on 2019-05-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='total_view_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='view_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
