# Generated by Django 2.1.7 on 2019-04-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20190423_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='pic_url',
            field=models.CharField(default='empty', max_length=200),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.CharField(default='empty', max_length=200),
        ),
    ]
