# Generated by Django 2.1.7 on 2019-04-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20190423_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='pic_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
